### ISSUE TITLE
32.768KHz晶振(12pf) 这个是不是标错了

### ISSUE THREAD

**Issue by z748807622** [SeasonWings/LINGNITHM#3]
目前还没听说过哪家晶振工厂生产过标称负载电容CL为12pF的32.768KHz晶体谐振器。
                         --- https://www.genuway.com/5892.html

**Comment by SeasonWings** [comment]
【淘宝】https://m.tb.cn/h.gdq8Dbz5Q3gkTW3?tk=hzdYWvTJrJz CZ8908 「3215贴片无源晶振 2脚 32.768KHZ 20PPM FC-135 6PF 9PF 12.5PF」实则12.5PF，EDA标12PF
